POST http://localhost:3000/users
content-type: application/json

{
    "email": "john.doe@email.com",
    "password": "123456",
    "role": "ADMIN"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjczMTJjZDA2LWQzZDQtNDY1Ny1hMWYxLTk1MWU5MjFjNWZjMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODg0OTMyMiwiZXhwIjoxNjU4ODUwMjIyfQ.uYoAGg1eZ85SalGroj57Ex33VG4LOByQKmLXcormB-7vVVkchOaWcmoPaIYCPLKoxeEGXIiysgHg5_AFk741-wLhoR5hgakZU_YP9QaeKphdz-apttQjdLRnny_z0FAZSOmdrZsi82E92jAlyxlR2rmlzRh7chVHFSWes6s3VunDJaauLaWDxSyWB4CH800uUCVpMmVBONpen9Ee0j-1cvnf0xzAxVGLCHp00ZrASu8KDgVbPiLDVEnwHUON1k_Mx_Brw8bJtmOIMi4__pRl95wzNKeqjBa1V9Hz_3kl7oBrX_G0hwUaSHFV54-GVxCK3HY48dKOKvSn3P2ZpEEoCA

###
POST http://localhost:3000/auth
content-type: application/json

{
    "email": "john.doe@email.com",
    "password": "123456"
}

###
POST http://localhost:3000/auth/refresh

###
POST http://localhost:3000/auth/logout
content-type: application/json

{
    "allDevices": true
}